### ISSUE TITLE
Incorporating rules into official eslint-plugin-vue

### ISSUE THREAD

**Issue by chrisvfritz** [mysticatea/eslint-plugin-vue-trial#3]
Love the work here! We're looking at incorporating at least some of these rules into the official `eslint-plugin-vue`, so was wondering: are all these rules (or a subset of them) currently considered stable? If so, do you recommend simply requiring this plugin to import the rules we want - or is this repo more of a playground for experimentation?

Again, thanks for the fantastic work!

**Comment by mysticatea** [comment]
Thank you for this issue!

Sure, I have a plan to send those rules to the official `eslint-plugin-vue` plugin.

This plugin was a playground for [vue-eslint-parser] then I have found some problems<sup>[1]</sup> in [vue-eslint-parser]. I'm trying to resolve the problems now. It's going to change the template AST that those rules are using, so my plan is that I send rules after I solved the parser's problems.

[1]: [vue-eslint-parser] is using [parse5] to parse HTML. However, [parse5] drops useful information for linting. E.g. duplicate attributes, illegal end tags, etc... Additionally, The design of [parse5]'s tokens are much different to what ESLint is using. It also is what I want to solve for stylistic rules.

[vue-eslint-parser]: https://github.com/mysticatea/vue-eslint-parser
[parse5]: https://github.com/inikulin/parse5

**Comment by mysticatea** [comment]
FYI: I will not make breaking changes without major version up (minor for `0.x`), so feel free to use this plugin with `^0.2.0` notation until I send rules to the official plugin.

**Comment by chrisvfritz** [comment]
That makes things very simple! And I'm excited even beyond the implications for Vue, if you're working on more robust HTML/XML parsing support for ESLint.

I'll close for now, but let you know if I have any other questions. If there's anything I can do to help from the Vue end, also please don't hesitate to tell me.
